### ISSUE TITLE
Screenshots must show default elementary OS settings

### ISSUE THREAD

**Issue by danrabbit** [panosx2/brightness#29]
I've marked the latest release of brightness as "Needs fixing" since its screenshot does not show elementary OS default settings.

Screenshots in AppCenter must show default settings, including Gtk+ stylesheets and window control positions.

---
For more information about publishing requirements, see [this page](https://github.com/elementary/houston/wiki/Before-You-Publish)

**Comment by panosx2** [comment]
ok i'll fix it. thanx :)
